# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Pillzy' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Pillzy
pod 'Firebase/Firestore'
pod 'FirebaseFirestoreSwift'
pod 'Firebase/Auth'

end

target 'PillzyWatch' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PillzyWatch

end

target 'PillzyWatch Extension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PillzyWatch Extension

end
